### ISSUE TITLE
sdk tcl build script

### ISSUE THREAD

**Issue by julianmartinenzsou** [fpgadeveloper/zedboard-axi-dma#2]
running on vivado 2016.2 the tcl script creating SDK worspace give the next error:
invalid command name "setws"

P.D. the batch is not running because didn´t found the paths.

any workaround without intalling the vivado 2016.4?.

**Comment by fpgadeveloper** [comment]
If you are using Vivado 2016.2 you should be using an earlier commit of the repo. The current sources will only work in Vivado 2016.4.

**Comment by julianmartinenzsou** [comment]
Thanks and sorry for my mistake.

The install instructions are the same like in the 2016.4 version?.

Regards.
